apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
- namespace.yaml
- secret.yaml
- deployment.yaml
- networkpolicy.yaml
- networkpolicy-block-http-https.yaml
- poddisruptionbudget.yaml
- triggerauthentication.yaml
- keda-scaledobject.yaml
- kyverno-block-http-https.yaml
