apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
- namespace.yaml
- secret.yaml
- deployment.yaml
- networkpolicy.yaml
- networkpolicy-block-http-https.yaml
- poddisruptionbudget.yaml
- triggerauthentication.yaml
- serviceaccount.yaml
- keda-scaledobject.yaml
- kyverno-policy-block-http-https.yaml
- kyverno-policy-image-security.yaml
- kyverno-policy-security-context.yaml
- kyverno-policy-required-labels.yaml
- kyverno-policy-resources-probes.yaml
- kyverno-policy-auto-mutate.yaml
- kyverno-policy-secrets-validation.yaml
- kyverno-policy-exception-policy-reporter.yaml
