apiVersion: v1
kind: Service
metadata:
  name: keda-kafka-consumer
  namespace: dev
  labels:
    app: keda-kafka-consumer
    component: consumer
spec:
  selector:
    app: keda-kafka-consumer
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
